nfsMounter:
  mounts:
    - nfsserver1:/export/pool0/homes=/data/homes/prod

jupyterhub:
  proxy:
    https:
      hosts:
        - datahub.berkeley.edu
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 40Gi
  singleuser:
    storage:
      extraVolumes:
        - name: home
          hostPath:
            path: /data/homes/prod/{username}
        - name: cogneuro
          hostPath:
            path: /data/homes/prod/_cogneuro
      extraVolumeMounts:
        - name: home
          mountPath: /home/jovyan
        - name: cogneuro
          mountPath: /data/cogneuro
          readOnly: True
